export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const SETTINGS_LOADED = 'SETTINGS_LOADED';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SET_LOADING = 'SET_LOADING';
export const SET_LOADING_SETTINGS = 'SET_LOADING_SETTINGS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SETTINGS_ERROR = 'SETTINGS_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const USER_PROFILE_LOADED = 'USER_PROFILE_LOADED';
export const SET_LOADING_USER_PROFILE = 'SET_LOADING_USER_PROFILE';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

export const GET_MESSAGES = 'GET_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const SET_LOADING_MESSAGES = 'SET_LOADING_MESSAGES';
export const SET_LOADING_SEND_MESSAGE = 'SET_LOADING_SEND_MESSAGE';
export const GET_MESSAGES_ERROR = 'GET_MESSAGES_ERROR';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
export const TOGGLE_FAV_ERROR = 'TOGGLE_FAV_ERROR';
